/** Site-wide legal entity & support contact (footer, emails, legal pages, API). */

export const LEGAL_COMPANY_NAME = 'Stratum Technologies LLC';

export const SUPPORT_EMAIL = 'supportstratum@gmail.com';
export const SUPPORT_MAILTO = `mailto:${SUPPORT_EMAIL}`;

/** Opens the user's mail app with a pre-filled support message (no server SMTP). */
export function buildFeedbackMailto({ name, email, message }) {
  const subject = `[STRATUM.ai] Feedback from ${String(name ?? '').trim().slice(0, 120)}`;
  const body = [
    `Name: ${String(name ?? '').trim()}`,
    `Email: ${String(email ?? '').trim()}`,
    '',
    String(message ?? '').trim(),
  ].join('\n');
  const params = new URLSearchParams();
  params.set('subject', subject);
  params.set('body', body.slice(0, 6000));
  return `${SUPPORT_MAILTO}?${params.toString()}`;
}
export const SUPPORT_PHONE = '(307) 295-0454';
export const SUPPORT_PHONE_TEL = `tel:${SUPPORT_PHONE.replace(/\D/g, '')}`;
export const CONTACT_SUPPORT_LABEL = 'Contact support';

export const REGISTERED_AGENT_NAME = 'Registered Agents Inc';
export const REGISTERED_AGENT_ADDRESS = '30 N Gould St Ste R, Sheridan, WY 82801, USA';

export const MAILING_ADDRESS = '30 N Gould St #28330, Sheridan, WY 82801, USA';
export const PRINCIPAL_OFFICE_ADDRESS = MAILING_ADDRESS;

/** Public-facing business / correspondence address (principal office). */
export const BUSINESS_ADDRESS = PRINCIPAL_OFFICE_ADDRESS;

export const COPYRIGHT_LINE = `© 2026 ${LEGAL_COMPANY_NAME}. Registered in Wyoming, USA. All rights reserved. ${BUSINESS_ADDRESS}`;

export const COPYRIGHT_SHORT = `© 2026 ${LEGAL_COMPANY_NAME}. Registered in Wyoming, USA.`;

export const EMAIL_LEGAL_FOOTER = `${LEGAL_COMPANY_NAME}, ${BUSINESS_ADDRESS}`;

export const PDF_BRAND_TAGLINE = 'Generated by STRATUM.ai — Your Roadmap to Band 9.0';
export const PDF_LEGAL_LINE = `${LEGAL_COMPANY_NAME} · ${BUSINESS_ADDRESS}`;
export const PDF_CONTACT_LINE = `${CONTACT_SUPPORT_LABEL}: ${SUPPORT_EMAIL}`;
