import { useEffect, useState } from 'react';

export function useWriterPersistence({
  workspaceStorageKey,
  draftStorageKey,
  setEssayT1,
  setEssayT2,
  setPromptT1Academic,
  setPromptT1Letter,
  setPromptT2,
  setActiveTab,
  setImage,
  setTask1Kind,
  setLetterMeta,
  setResultT1,
  setResultT2,
  setCurrentTopic,
  setIsAutoGenerated,
  setIsImageCollapsed,
  essayT1,
  essayT2,
  activeTab,
  promptT1Academic,
  promptT1Letter,
  promptT2,
  image,
  task1Kind,
  letterMeta,
  activeResultT1,
  activeResultT2,
  currentTopic,
  isAutoGenerated,
  isImageCollapsed,
}) {
  const [workspaceReady, setWorkspaceReady] = useState(false);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    setWorkspaceReady(false);
    try {
      const wsRaw = localStorage.getItem(workspaceStorageKey);
      if (wsRaw) {
        const w = JSON.parse(wsRaw);
        if (typeof w.t1 === 'string') setEssayT1(w.t1);
        if (typeof w.t2 === 'string') setEssayT2(w.t2);
        if (typeof w.promptT1Academic === 'string') setPromptT1Academic(w.promptT1Academic);
        if (typeof w.promptT1Letter === 'string') setPromptT1Letter(w.promptT1Letter);
        if (typeof w.promptT2 === 'string') setPromptT2(w.promptT2);
        if (typeof w.promptT1 === 'string' && !w.promptT1Academic && !w.promptT1Letter) {
          if (w.task1Kind === 'gt_letter') setPromptT1Letter(w.promptT1);
          else setPromptT1Academic(w.promptT1);
        }
        const savedTab = w.activeTab === 'Topics' ? 'Home' : w.activeTab;
        if (
          typeof savedTab === 'string' &&
          (savedTab === 'Task 1' || savedTab === 'Task 2' || savedTab === 'Home' || savedTab === 'Bank')
        ) {
          setActiveTab(savedTab);
        }
        if (Object.prototype.hasOwnProperty.call(w, 'image')) setImage(w.image);
        if (w.task1Kind === 'gt_letter' || w.task1Kind === 'academic') setTask1Kind(w.task1Kind);
        if (w.letterMeta && typeof w.letterMeta === 'object') {
          setLetterMeta((prev) => ({ ...prev, ...w.letterMeta }));
        }
        if (Object.prototype.hasOwnProperty.call(w, 'resultT1')) setResultT1(w.resultT1);
        if (Object.prototype.hasOwnProperty.call(w, 'resultT2')) setResultT2(w.resultT2);
        if (Object.prototype.hasOwnProperty.call(w, 'currentTopic')) setCurrentTopic(w.currentTopic);
        if (typeof w.isAutoGenerated === 'boolean') setIsAutoGenerated(w.isAutoGenerated);
        if (typeof w.isImageCollapsed === 'boolean') setIsImageCollapsed(w.isImageCollapsed);
      } else {
        const draft = localStorage.getItem(draftStorageKey);
        if (draft) {
          const { t1, t2 } = JSON.parse(draft);
          setEssayT1(t1 || '');
          setEssayT2(t2 || '');
        }
      }
    } catch (e) {
      console.warn('Workspace restore failed', e);
    }
    setWorkspaceReady(true);
  }, [workspaceStorageKey, draftStorageKey]);

  useEffect(() => {
    if (typeof window === 'undefined' || !workspaceReady) return;
    try {
      const payload = {
        v: 2,
        t1: essayT1,
        t2: essayT2,
        activeTab,
        promptT1Academic,
        promptT1Letter,
        promptT2,
        image,
        task1Kind,
        letterMeta,
        resultT1: activeResultT1,
        resultT2: activeResultT2,
        currentTopic,
        isAutoGenerated,
        isImageCollapsed,
      };
      localStorage.setItem(workspaceStorageKey, JSON.stringify(payload));
      localStorage.setItem(draftStorageKey, JSON.stringify({ t1: essayT1, t2: essayT2 }));
    } catch (e) {
      console.warn('Workspace persist failed (quota or private mode)', e);
    }
  }, [
    workspaceReady,
    essayT1,
    essayT2,
    promptT1Academic,
    promptT1Letter,
    promptT2,
    image,
    task1Kind,
    letterMeta,
    activeResultT1,
    activeResultT2,
    activeTab,
    currentTopic,
    isAutoGenerated,
    isImageCollapsed,
    workspaceStorageKey,
    draftStorageKey,
  ]);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    const onWorkspacePatch = (e) => {
      const w = e?.detail;
      if (!w || typeof w !== 'object') return;
      if (typeof w.t1 === 'string') setEssayT1(w.t1);
      if (typeof w.t2 === 'string') setEssayT2(w.t2);
    };
    window.addEventListener('ielts-stratum-workspace-patch', onWorkspacePatch);
    return () => window.removeEventListener('ielts-stratum-workspace-patch', onWorkspacePatch);
  }, [setEssayT1, setEssayT2]);

  return { workspaceReady };
}
