import { useState } from 'react';
import toast from 'react-hot-toast';
import { TASK1_ASSETS } from '@/lib/writer/constants';
import { generateTask2Topic } from '@/lib/writer/generateTask2Topic';
import { parseCheckApiError } from '@/lib/writer/checkApiErrors';
import {
  describeChartImage,
  generateLetterTaskRequest,
  readImageAsDataUrl,
} from '@/lib/writer/writerApi';

export function useWriterTaskGeneration({
  customKeyword,
  setPromptT2,
  setCurrentTopic,
  setIsAutoGenerated,
  setActiveTab,
  setTask1Kind,
  setPromptT1Academic,
  setPromptT1Letter,
  setImage,
  setAuthModalMessage,
  setIsAuthOpen,
  setError,
  setErrorIs401,
}) {
  const [genLoading, setGenLoading] = useState(false);
  const [genTopicError, setGenTopicErrorLocal] = useState(null);
  const [isGenLoadingT1, setIsGenLoadingT1] = useState(false);
  const [isGenLoadingLetter, setIsGenLoadingLetter] = useState(false);
  const [isDescribing, setIsDescribing] = useState(false);
  const [imageUploadError, setImageUploadError] = useState(null);

  const setTopicError = (msg) => {
    setGenTopicErrorLocal(msg);
  };

  const handleImageUpload = async (fileOrUrl) => {
    setIsDescribing(true);
    setImageUploadError(null);
    try {
      const isUrl = typeof fileOrUrl === 'string';
      const imageData = isUrl ? fileOrUrl : await readImageAsDataUrl(fileOrUrl);

      setImage(imageData);

      const data = await describeChartImage(imageData);
      const question = data?.question;
      if (question) {
        setTask1Kind('academic');
        setPromptT1Academic(question);
        setIsAutoGenerated(true);
      } else if (data?.error) {
        setImageUploadError(data.error);
      } else if (!data || (typeof data === 'object' && Object.keys(data).length === 0)) {
        setImageUploadError('Empty server response. Please try again.');
      }
    } catch (e) {
      const parsed = parseCheckApiError(e, { authMessage: 'Sign in to analyze chart images.' });
      if (parsed.isAuthRequired) {
        setAuthModalMessage(parsed.display);
        setIsAuthOpen(true);
        setImageUploadError(parsed.display);
        return;
      }
      if (parsed.isApiKeyError) {
        setImageUploadError(parsed.display);
        return;
      }
      if (parsed.is401) {
        setErrorIs401(true);
        setError(parsed.display);
      }
      setImageUploadError(parsed.display);
    } finally {
      setIsDescribing(false);
    }
  };

  const handleGenerateTask2 = async () => {
    if (!customKeyword.trim()) {
      alert('Keyword required');
      return;
    }
    setGenLoading(true);
    setTopicError(null);
    try {
      const result = await generateTask2Topic(customKeyword);
      if (result.ok) {
        setPromptT2(result.question);
        setCurrentTopic({ name: 'AI Topic', q: result.question });
        setIsAutoGenerated(true);
        setActiveTab('Task 2');
        window.scrollTo({ top: 0, behavior: 'smooth' });
      } else {
        setTopicError(result.error);
      }
    } catch (e) {
      const parsed = parseCheckApiError(e, { authMessage: 'Sign in to generate AI topics.' });
      if (parsed.isAuthRequired) {
        setAuthModalMessage(parsed.display);
        setIsAuthOpen(true);
      }
      setTopicError(parsed.display);
    } finally {
      setGenLoading(false);
    }
  };

  const generateTask1Data = async () => {
    setTask1Kind('academic');
    setIsGenLoadingT1(true);
    try {
      const categories = Object.keys(TASK1_ASSETS);
      const randomCat = categories[Math.floor(Math.random() * categories.length)];
      const assets = TASK1_ASSETS[randomCat];
      const randomUrl = Array.isArray(assets) ? assets[Math.floor(Math.random() * assets.length)] : assets;
      await handleImageUpload(randomUrl);
      setActiveTab('Task 1');
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenLoadingT1(false);
    }
  };

  const generateLetterTask = async () => {
    setIsGenLoadingLetter(true);
    try {
      const data = await generateLetterTaskRequest();
      const question = data?.question;
      if (question) {
        setTask1Kind('gt_letter');
        setPromptT1Letter(question);
        setIsAutoGenerated(true);
        setActiveTab('Task 1');
        window.scrollTo({ top: 0, behavior: 'smooth' });
      } else {
        toast.error(data?.error || 'Could not generate letter task.');
      }
    } catch (e) {
      const parsed = parseCheckApiError(e, { authMessage: 'Sign in to generate letter tasks.' });
      if (parsed.isApiKeyError) {
        toast.error(parsed.display);
        return;
      }
      toast.error(parsed.display || 'Letter task generation failed.');
    } finally {
      setIsGenLoadingLetter(false);
    }
  };

  return {
    genLoading,
    genTopicError,
    setGenTopicError: setGenTopicErrorLocal,
    isGenLoadingT1,
    isGenLoadingLetter,
    isDescribing,
    imageUploadError,
    setImageUploadError,
    handleImageUpload,
    handleGenerateTask2,
    generateTask1Data,
    generateLetterTask,
  };
}
